name: Build, Test, Dockerize & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- Python / Flask Tests ---
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        cd flask
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Flask tests
      run: |
        cd flask
        source venv/bin/activate
        pytest

    # --- Go Tests ---
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run Go tests
      run: |
        cd go
        go test ./...

    # --- Docker Build & Push ---
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build . -t my-image-name:latest -t my-image-name:${{ steps.vars.outputs.sha_short }}

    - name: Push Docker images
      run: |
        docker tag my-image-name:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
        docker tag my-image-name:${{ steps.vars.outputs.sha_short }} ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:${{ steps.vars.outputs.sha_short }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:${{ steps.vars.outputs.sha_short }}
