name: Go Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run Go tests
      run: go test ./...

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build . -t omkumar2003/interpreter:latest -t omkumar2003/interpreter:${{ steps.vars.outputs.sha_short }}

    - name: Push Docker images
      run: |
        docker push omkumar2003/interpreter:latest
        docker push omkumar2003/interpreter:${{ steps.vars.outputs.sha_short }}
